### ISSUE TITLE
Stasher / Removing cache entries

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/drafter#221]
Currently the stasher cache just grows indefinitely.

We should implement a policy to remove cache entries when the size of the cache passes a certain threshold.

We may also wish to remove items based on a function of cost to generate and last access time...  We might want to store information on the queries/cache-hits/access-times etc in another database.

Updates to this database can be queued and flushed periodically to disk so need not be on the main execution path.

Will likely require two threads, one to flush the datbase to disk if there were any cached items created, and the other to query the database and purge items periodically.

- [x] #241 - File names
- [x] #242 - Cache hit times
- [x] #243 - Cache cleaner
- [x] #244 - Cache cleaner scheduling
- [x]  #245 - Safe cache entry deletion (i.e. don't disrupt any ongoing reads from deleting the file from under them) 
- [x] #246 - Log events to Datadog
